name: ebbot_flutter_ui_demo
description: "A ebbot flutter ui demo app."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ebbot_flutter_ui:
    git:
      url: https://github.com/ebbot-ai/ebbot_flutter_ui
      ref: v0.1.1

  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  flutter_chat_ui: ^1.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env